[package]
name = "dominant_color_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dominant_color = "0.3.0"
tokio = { version = "1", features = ["full"] }
warp = "0.3"
